apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  namespace: droneci
  labels:
    io.kompose.service: drone-server-claim11
  name: drone-server-claim11
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
