apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: droneci
  labels:
    io.kompose.service: drone-agent
  name: drone-agent
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: drone-agent
status:
  loadBalancer: {}
